name: 'Post to Bluesky'

on:
  workflow_dispatch: # allow manual triggering
  schedule:
    # auto runs every 6 hours
    - cron: '0 */6 * * *'

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Posting to Bluesky...
        run: pnpm start
