name: 'Post to Bluesky'

on:
  workflow_dispatch: # allow manual triggering
  schedule:
    # auto runs every 6 hours
    - cron: '0 */6 * * *'

permissions:
  contents: read

jobs:
  build-and-run:
    name: Build and run bot 🤖
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.7.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Posting to Bluesky...
        run: pnpm start
        env:
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          BSKY_NOCONTEXTSCATS_HANDLE: ${{ secrets.BSKY_NOCONTEXTSCATS_HANDLE }}
          BSKY_NOCONTEXTSCATS_PASSWORD: ${{ secrets.BSKY_NOCONTEXTSCATS_PASSWORD }}
